services:
  api:
    container_name: "formatter-service-api"
    image: ghcr.io/tef-austral/echo:latest #T0DO CHANGE
    ports:
      - 8001:8080
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: formatter_db
    image: postgres:16
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
